##################################################################################################
# Balance service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: akililab-balance
  labels:
    app: akililab-balance
    service: akililab-balance
spec:
  ports:
  - port: 9080
    name: gprc
  selector:
    app: akililab-balance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: akililab-balance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akililab-balance-v1
  labels:
    app: akililab-balance
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akililab-balance
      version: v1
  template:
    metadata:
      labels:
        app: akililab-balance
        version: v1
    spec:
      serviceAccountName: akililab-balance
      containers:
      - name: akililab-balance
        image: gcr.io/akililab-pay/balance:4205a0faf2b85015c7736e48827ac6d14b799006
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---