apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: gcr.io/knative-akili/github.com/akililab/api-gateway:da4ded1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
          - name: BALANCE_ADDRESS
            value: balance.dev:9098
          - name: TRANSACTION_ADDRESS
            value: balance.dev:50052
          - name: ACCOUNT_ADDRESS
            value: account.dev:50051

---

kind: Service
apiVersion: v1
metadata:
  name: apigateway
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: apigateway