# TCPRoute for apigateway Service
---
apiVersion: specs.smi-spec.io/v1alpha1
kind: TCPRoute
metadata:
  name: apigateway-tcp-route

# TrafficTarget defines allowed routes for ambassador
# In this example apigateway is allow to connect using
# TCP
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: apigateway-targets
  namespace: default
destination:
  kind: ServiceAccount
  name: apigateway
  namespace: default
sources:
- kind: ServiceAccount
  name: ambassador
  namespace: default
specs:
- kind: TCPRoute
  name: apigateway-tcp-route

# TCPRoute for Balance Service.
---
apiVersion: specs.smi-spec.io/v1alpha1
kind: TCPRoute
metadata:
  name: service-balance-tcp-route

# TrafficTarget defines allowed routes for balance.
# In this example apigateway is allow to connect using
# TCP.
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: balance-traffic-target
  namespace: default
destination:
  kind: ServiceAccount
  name: balance
  namespace: default
sources:
- kind: ServiceAccount
  name: apigateway
  namespace: default
specs:
- kind: TCPRoute
  name: service-balance-tcp-route