---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: balance
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigateway
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction
automountServiceAccountToken: false