apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: balance
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: balance
    spec:
      containers:
      - name: balance
        image: gcr.io/akililab-pay/balance:42e6622ac0eb4e0b517f31067b497874ede7df69
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
          name: grpc-port

---

kind: Service
apiVersion: v1
metadata:
  name: balance
spec:
  ports:
  - name: grpc-balance
    port: 9080
    targetPort: 9080
  selector:
    app: balance