
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: balance
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: balance
    spec:
      containers:
      - name: balance
        image: gcr.io/akililab-pay/balance:4205a0faf2b85015c7736e48827ac6d14b799006
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
          name: grpc-port
          protocol: GRPC

---

kind: Service
apiVersion: v1
metadata:
  name: balance
spec:
  ports:
  - name: grpc-balance
    port: 9080
    targetPort: 9080
  selector:
    app: balance